### ISSUE TITLE
Custom sell/buy gui issue

### ISSUE THREAD

**Issue by PixelFen** [Nowaha/Shop-by-Conjurate#14]
I setup a new sell shop and set the shop to the name of it and when i go and try to get the sell gui, nothing happens. and when i go into the console i see `Could not pass event PageClickEvent to Shop v2.5.0
java.lang.NullPointerException: null`

**Comment by Huskehhh** [comment]
Is there more to the stacktrace?

**Comment by PixelFen** [comment]
that's all it shows in console.

Edit:
Its now giving more info than before.

```
[21:43:05 ERROR]: Could not pass event PageClickEvent to Shop v2.5.0
java.lang.NullPointerException: null
at java.util.regex.Matcher.appendReplacement(Matcher.java:804) ~[?:1.8.0_222]
at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_222]
at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_222]
at conj.shop.addons.Placeholder.placehold(Placeholder.java:49) ~[?:?]
at conj.shop.addons.Placeholder.placehold(Placeholder.java:33) ~[?:?]
at conj.shop.addons.Placeholder.placehold(Placeholder.java:190) ~[?:?]
at conj.shop.events.listeners.Shop.sellItem(Shop.java:570) ~[?:?]
at conj.shop.events.listeners.Shop.ItemviewClick(Shop.java:237) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor375.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[minecraft_server.jar:git-Paper-225]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[minecraft_server.jar:git-Paper-225]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Paper-225]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[minecraft_server.jar:git-Paper-225]
at conj.shop.events.listeners.GUI.lambda$InteractEditor$1(GUI.java:138) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[minecraft_server.jar:git-Paper-225]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[minecraft_server.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[minecraft_server.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[minecraft_server.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[minecraft_server.jar:git-Paper-225]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[minecraft_server.jar:git-Paper-225]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by PixelFen** [comment]
Okay I found out the issue. I used a unicode thingy and its breaking the shop so it was just an issue on my end. Its working fine now.
