### ISSUE TITLE
1.15 support

### ISSUE THREAD

**Issue by dekejr** [Nowaha/Shop-by-Conjurate#18]
1.15 has broken the shop again xD. I'm hoping you can get this fixed?

**Comment by Huskehhh** [comment]
More info please, an error or something

**Comment by dekejr** [comment]
Could not pass event PageClickEvent to Shop v2.1.5-SNAPSHOT
java.lang.NullPointerException: null
	at conj.shop.events.listeners.Shop.inventoryContains(Shop.java:672) ~[?:?]
	at conj.shop.events.listeners.Shop.ItemviewClick(Shop.java:234) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor356.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-26]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-26]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-26]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-26]
	at conj.shop.events.listeners.GUI.lambda$InteractEditor$1(GUI.java:140) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-26]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-26]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-26]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-26]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-26]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-26]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Huskehhh** [comment]
When does that error pop up? When you click any item? or an empty slot?

**Comment by dekejr** [comment]
you can buy things but when you click on something(item) to sell it produces that error.

**Comment by Huskehhh** [comment]
Unable to replicate, please test latest build
