### ISSUE TITLE
Cannot buy items (Shop 1.15.2)

### ISSUE THREAD

**Issue by Hellcode48** [Nowaha/Shop-by-Conjurate#33]
When I click on the item to purchase I get this error in console:

`Could not pass event PageClickEvent to Shop v2.1.5-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	at conj.shop.events.listeners.GUI.lambda$InteractEditor$1(GUI.java:140) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1015) ~[?:?]
	at java.util.regex.Matcher.appendReplacement(Matcher.java:998) ~[?:?]
	at java.util.regex.Matcher.replaceAll(Matcher.java:1182) ~[?:?]
	at java.lang.String.replaceAll(String.java:2126) ~[?:?]
	at conj.shop.addons.Placeholder.placehold(Placeholder.java:49) ~[?:?]
	at conj.shop.addons.Placeholder.placehold(Placeholder.java:33) ~[?:?]
	at conj.shop.addons.Placeholder.placehold(Placeholder.java:190) ~[?:?]
	at conj.shop.events.listeners.Shop.buyItem(Shop.java:531) ~[?:?]
	at conj.shop.events.listeners.Shop.ItemviewClick(Shop.java:230) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor1037.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
	... 11 more`

**Comment by Hellcode48** [comment]
Turns out it happens with any of the placeholders from the plugin
