### ISSUE TITLE
plugin wont load

### ISSUE THREAD

**Issue by WesleyVanNeck** [Nowaha/Shop-by-Conjurate#34]
paper 1.15.2 latest citzens

`[10:54:42] [Server thread/ERROR]: Error occurred while enabling Shop v2.5.0 (Is it up to date?)
java.lang.IllegalStateException: no implementation set
	at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:68) ~[?:?]
	at net.citizensnpcs.api.CitizensAPI.getTraitFactory(CitizensAPI.java:148) ~[?:?]
	at conj.shop.Initiate.onEnable(Initiate.java:157) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-298]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-298]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-298]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-298]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-298]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-298]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-298]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-298]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
`

**Comment by BlackBeltPanda** [comment]
Try this build of Shop: https://ci.husk.pro/job/Shop-By-Conjurate/

**Comment by WesleyVanNeck** [comment]
still  happens

**Comment by TheRobLP** [comment]
Hey, BlackBelt. I am Legacy´s partner on our server. I just wanted to inform you that it was solved. Not sure why it didn´t work the first time, but now it does

**Comment by WesleyVanNeck** [comment]
thnx @TheRobLP
